version: "3"
services:
  go:
    image: yaserdarzi/phonebookgo
    ports:
    - 5050:5050
    depends_on:
    - mongo
    env_file:
    - go.env
    - jwt.env
    - mongo.env
  mongo:
    image: mongo:3.7
volumes:
  phonebook-mongo: